/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as QaRouteRouteImport } from './routes/qa/route'
import { Route as AnnotatorRouteRouteImport } from './routes/annotator/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QaIndexRouteImport } from './routes/qa/index'
import { Route as AnnotatorIndexRouteImport } from './routes/annotator/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as QaDashboardRouteImport } from './routes/qa/dashboard'
import { Route as AnnotatorDashboardRouteImport } from './routes/annotator/dashboard'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminJobAssignmentRouteImport } from './routes/admin/job-assignment'
import { Route as AdminExportRouteImport } from './routes/admin/export'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAnnotationClassesRouteImport } from './routes/admin/annotation-classes'
import { Route as AdminDatasetsIndexRouteImport } from './routes/admin/datasets/index'
import { Route as AdminDatasetsIdRouteImport } from './routes/admin/datasets/$id'
import { Route as QaJobsJobIdReviewRouteImport } from './routes/qa/jobs/$jobId/review'
import { Route as QaJobsJobIdHistoryRouteImport } from './routes/qa/jobs/$jobId/history'
import { Route as AnnotatorJobsJobIdHistoryRouteImport } from './routes/annotator/jobs/$jobId/history'
import { Route as AnnotatorJobsJobIdAnnotateRouteImport } from './routes/annotator/jobs/$jobId/annotate'
import { Route as AdminJobsJobIdHistoryRouteImport } from './routes/admin/jobs/$jobId/history'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRouteRoute = QaRouteRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnotatorRouteRoute = AnnotatorRouteRouteImport.update({
  id: '/annotator',
  path: '/annotator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaIndexRoute = QaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QaRouteRoute,
} as any)
const AnnotatorIndexRoute = AnnotatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnnotatorRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const QaDashboardRoute = QaDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => QaRouteRoute,
} as any)
const AnnotatorDashboardRoute = AnnotatorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AnnotatorRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobAssignmentRoute = AdminJobAssignmentRouteImport.update({
  id: '/job-assignment',
  path: '/job-assignment',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnnotationClassesRoute = AdminAnnotationClassesRouteImport.update({
  id: '/annotation-classes',
  path: '/annotation-classes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDatasetsIndexRoute = AdminDatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDatasetsIdRoute = AdminDatasetsIdRouteImport.update({
  id: '/datasets/$id',
  path: '/datasets/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const QaJobsJobIdReviewRoute = QaJobsJobIdReviewRouteImport.update({
  id: '/jobs/$jobId/review',
  path: '/jobs/$jobId/review',
  getParentRoute: () => QaRouteRoute,
} as any)
const QaJobsJobIdHistoryRoute = QaJobsJobIdHistoryRouteImport.update({
  id: '/jobs/$jobId/history',
  path: '/jobs/$jobId/history',
  getParentRoute: () => QaRouteRoute,
} as any)
const AnnotatorJobsJobIdHistoryRoute =
  AnnotatorJobsJobIdHistoryRouteImport.update({
    id: '/jobs/$jobId/history',
    path: '/jobs/$jobId/history',
    getParentRoute: () => AnnotatorRouteRoute,
  } as any)
const AnnotatorJobsJobIdAnnotateRoute =
  AnnotatorJobsJobIdAnnotateRouteImport.update({
    id: '/jobs/$jobId/annotate',
    path: '/jobs/$jobId/annotate',
    getParentRoute: () => AnnotatorRouteRoute,
  } as any)
const AdminJobsJobIdHistoryRoute = AdminJobsJobIdHistoryRouteImport.update({
  id: '/jobs/$jobId/history',
  path: '/jobs/$jobId/history',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/annotator': typeof AnnotatorRouteRouteWithChildren
  '/qa': typeof QaRouteRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/annotation-classes': typeof AdminAnnotationClassesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/job-assignment': typeof AdminJobAssignmentRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/annotator/dashboard': typeof AnnotatorDashboardRoute
  '/qa/dashboard': typeof QaDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/annotator/': typeof AnnotatorIndexRoute
  '/qa/': typeof QaIndexRoute
  '/admin/datasets/$id': typeof AdminDatasetsIdRoute
  '/admin/datasets/': typeof AdminDatasetsIndexRoute
  '/admin/jobs/$jobId/history': typeof AdminJobsJobIdHistoryRoute
  '/annotator/jobs/$jobId/annotate': typeof AnnotatorJobsJobIdAnnotateRoute
  '/annotator/jobs/$jobId/history': typeof AnnotatorJobsJobIdHistoryRoute
  '/qa/jobs/$jobId/history': typeof QaJobsJobIdHistoryRoute
  '/qa/jobs/$jobId/review': typeof QaJobsJobIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/annotation-classes': typeof AdminAnnotationClassesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/job-assignment': typeof AdminJobAssignmentRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/annotator/dashboard': typeof AnnotatorDashboardRoute
  '/qa/dashboard': typeof QaDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/annotator': typeof AnnotatorIndexRoute
  '/qa': typeof QaIndexRoute
  '/admin/datasets/$id': typeof AdminDatasetsIdRoute
  '/admin/datasets': typeof AdminDatasetsIndexRoute
  '/admin/jobs/$jobId/history': typeof AdminJobsJobIdHistoryRoute
  '/annotator/jobs/$jobId/annotate': typeof AnnotatorJobsJobIdAnnotateRoute
  '/annotator/jobs/$jobId/history': typeof AnnotatorJobsJobIdHistoryRoute
  '/qa/jobs/$jobId/history': typeof QaJobsJobIdHistoryRoute
  '/qa/jobs/$jobId/review': typeof QaJobsJobIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/annotator': typeof AnnotatorRouteRouteWithChildren
  '/qa': typeof QaRouteRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/annotation-classes': typeof AdminAnnotationClassesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/job-assignment': typeof AdminJobAssignmentRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/annotator/dashboard': typeof AnnotatorDashboardRoute
  '/qa/dashboard': typeof QaDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/annotator/': typeof AnnotatorIndexRoute
  '/qa/': typeof QaIndexRoute
  '/admin/datasets/$id': typeof AdminDatasetsIdRoute
  '/admin/datasets/': typeof AdminDatasetsIndexRoute
  '/admin/jobs/$jobId/history': typeof AdminJobsJobIdHistoryRoute
  '/annotator/jobs/$jobId/annotate': typeof AnnotatorJobsJobIdAnnotateRoute
  '/annotator/jobs/$jobId/history': typeof AnnotatorJobsJobIdHistoryRoute
  '/qa/jobs/$jobId/history': typeof QaJobsJobIdHistoryRoute
  '/qa/jobs/$jobId/review': typeof QaJobsJobIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/annotator'
    | '/qa'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/unauthorized'
    | '/admin/annotation-classes'
    | '/admin/dashboard'
    | '/admin/export'
    | '/admin/job-assignment'
    | '/admin/settings'
    | '/admin/users'
    | '/annotator/dashboard'
    | '/qa/dashboard'
    | '/admin/'
    | '/annotator/'
    | '/qa/'
    | '/admin/datasets/$id'
    | '/admin/datasets/'
    | '/admin/jobs/$jobId/history'
    | '/annotator/jobs/$jobId/annotate'
    | '/annotator/jobs/$jobId/history'
    | '/qa/jobs/$jobId/history'
    | '/qa/jobs/$jobId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/unauthorized'
    | '/admin/annotation-classes'
    | '/admin/dashboard'
    | '/admin/export'
    | '/admin/job-assignment'
    | '/admin/settings'
    | '/admin/users'
    | '/annotator/dashboard'
    | '/qa/dashboard'
    | '/admin'
    | '/annotator'
    | '/qa'
    | '/admin/datasets/$id'
    | '/admin/datasets'
    | '/admin/jobs/$jobId/history'
    | '/annotator/jobs/$jobId/annotate'
    | '/annotator/jobs/$jobId/history'
    | '/qa/jobs/$jobId/history'
    | '/qa/jobs/$jobId/review'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/annotator'
    | '/qa'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/unauthorized'
    | '/admin/annotation-classes'
    | '/admin/dashboard'
    | '/admin/export'
    | '/admin/job-assignment'
    | '/admin/settings'
    | '/admin/users'
    | '/annotator/dashboard'
    | '/qa/dashboard'
    | '/admin/'
    | '/annotator/'
    | '/qa/'
    | '/admin/datasets/$id'
    | '/admin/datasets/'
    | '/admin/jobs/$jobId/history'
    | '/annotator/jobs/$jobId/annotate'
    | '/annotator/jobs/$jobId/history'
    | '/qa/jobs/$jobId/history'
    | '/qa/jobs/$jobId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AnnotatorRouteRoute: typeof AnnotatorRouteRouteWithChildren
  QaRouteRoute: typeof QaRouteRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annotator': {
      id: '/annotator'
      path: '/annotator'
      fullPath: '/annotator'
      preLoaderRoute: typeof AnnotatorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/': {
      id: '/qa/'
      path: '/'
      fullPath: '/qa/'
      preLoaderRoute: typeof QaIndexRouteImport
      parentRoute: typeof QaRouteRoute
    }
    '/annotator/': {
      id: '/annotator/'
      path: '/'
      fullPath: '/annotator/'
      preLoaderRoute: typeof AnnotatorIndexRouteImport
      parentRoute: typeof AnnotatorRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/qa/dashboard': {
      id: '/qa/dashboard'
      path: '/dashboard'
      fullPath: '/qa/dashboard'
      preLoaderRoute: typeof QaDashboardRouteImport
      parentRoute: typeof QaRouteRoute
    }
    '/annotator/dashboard': {
      id: '/annotator/dashboard'
      path: '/dashboard'
      fullPath: '/annotator/dashboard'
      preLoaderRoute: typeof AnnotatorDashboardRouteImport
      parentRoute: typeof AnnotatorRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/job-assignment': {
      id: '/admin/job-assignment'
      path: '/job-assignment'
      fullPath: '/admin/job-assignment'
      preLoaderRoute: typeof AdminJobAssignmentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/annotation-classes': {
      id: '/admin/annotation-classes'
      path: '/annotation-classes'
      fullPath: '/admin/annotation-classes'
      preLoaderRoute: typeof AdminAnnotationClassesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/datasets/': {
      id: '/admin/datasets/'
      path: '/datasets'
      fullPath: '/admin/datasets/'
      preLoaderRoute: typeof AdminDatasetsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/datasets/$id': {
      id: '/admin/datasets/$id'
      path: '/datasets/$id'
      fullPath: '/admin/datasets/$id'
      preLoaderRoute: typeof AdminDatasetsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/qa/jobs/$jobId/review': {
      id: '/qa/jobs/$jobId/review'
      path: '/jobs/$jobId/review'
      fullPath: '/qa/jobs/$jobId/review'
      preLoaderRoute: typeof QaJobsJobIdReviewRouteImport
      parentRoute: typeof QaRouteRoute
    }
    '/qa/jobs/$jobId/history': {
      id: '/qa/jobs/$jobId/history'
      path: '/jobs/$jobId/history'
      fullPath: '/qa/jobs/$jobId/history'
      preLoaderRoute: typeof QaJobsJobIdHistoryRouteImport
      parentRoute: typeof QaRouteRoute
    }
    '/annotator/jobs/$jobId/history': {
      id: '/annotator/jobs/$jobId/history'
      path: '/jobs/$jobId/history'
      fullPath: '/annotator/jobs/$jobId/history'
      preLoaderRoute: typeof AnnotatorJobsJobIdHistoryRouteImport
      parentRoute: typeof AnnotatorRouteRoute
    }
    '/annotator/jobs/$jobId/annotate': {
      id: '/annotator/jobs/$jobId/annotate'
      path: '/jobs/$jobId/annotate'
      fullPath: '/annotator/jobs/$jobId/annotate'
      preLoaderRoute: typeof AnnotatorJobsJobIdAnnotateRouteImport
      parentRoute: typeof AnnotatorRouteRoute
    }
    '/admin/jobs/$jobId/history': {
      id: '/admin/jobs/$jobId/history'
      path: '/jobs/$jobId/history'
      fullPath: '/admin/jobs/$jobId/history'
      preLoaderRoute: typeof AdminJobsJobIdHistoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnnotationClassesRoute: typeof AdminAnnotationClassesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminJobAssignmentRoute: typeof AdminJobAssignmentRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDatasetsIdRoute: typeof AdminDatasetsIdRoute
  AdminDatasetsIndexRoute: typeof AdminDatasetsIndexRoute
  AdminJobsJobIdHistoryRoute: typeof AdminJobsJobIdHistoryRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnnotationClassesRoute: AdminAnnotationClassesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExportRoute: AdminExportRoute,
  AdminJobAssignmentRoute: AdminJobAssignmentRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDatasetsIdRoute: AdminDatasetsIdRoute,
  AdminDatasetsIndexRoute: AdminDatasetsIndexRoute,
  AdminJobsJobIdHistoryRoute: AdminJobsJobIdHistoryRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AnnotatorRouteRouteChildren {
  AnnotatorDashboardRoute: typeof AnnotatorDashboardRoute
  AnnotatorIndexRoute: typeof AnnotatorIndexRoute
  AnnotatorJobsJobIdAnnotateRoute: typeof AnnotatorJobsJobIdAnnotateRoute
  AnnotatorJobsJobIdHistoryRoute: typeof AnnotatorJobsJobIdHistoryRoute
}

const AnnotatorRouteRouteChildren: AnnotatorRouteRouteChildren = {
  AnnotatorDashboardRoute: AnnotatorDashboardRoute,
  AnnotatorIndexRoute: AnnotatorIndexRoute,
  AnnotatorJobsJobIdAnnotateRoute: AnnotatorJobsJobIdAnnotateRoute,
  AnnotatorJobsJobIdHistoryRoute: AnnotatorJobsJobIdHistoryRoute,
}

const AnnotatorRouteRouteWithChildren = AnnotatorRouteRoute._addFileChildren(
  AnnotatorRouteRouteChildren,
)

interface QaRouteRouteChildren {
  QaDashboardRoute: typeof QaDashboardRoute
  QaIndexRoute: typeof QaIndexRoute
  QaJobsJobIdHistoryRoute: typeof QaJobsJobIdHistoryRoute
  QaJobsJobIdReviewRoute: typeof QaJobsJobIdReviewRoute
}

const QaRouteRouteChildren: QaRouteRouteChildren = {
  QaDashboardRoute: QaDashboardRoute,
  QaIndexRoute: QaIndexRoute,
  QaJobsJobIdHistoryRoute: QaJobsJobIdHistoryRoute,
  QaJobsJobIdReviewRoute: QaJobsJobIdReviewRoute,
}

const QaRouteRouteWithChildren =
  QaRouteRoute._addFileChildren(QaRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AnnotatorRouteRoute: AnnotatorRouteRouteWithChildren,
  QaRouteRoute: QaRouteRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
