# Generated by Django 5.2.11 on 2026-02-07 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("annotations", "0001_initial"),
        ("datasets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QAReviewVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "decision",
                    models.CharField(
                        choices=[("ACCEPT", "Accept"), ("REJECT", "Reject")],
                        max_length=10,
                    ),
                ),
                ("comments", models.TextField(blank=True, default="")),
                ("modifications_summary", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annotation_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_reviews",
                        to="annotations.annotationversion",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_reviews",
                        to="datasets.job",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qa_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "version_number")},
            },
        ),
    ]
