# Generated by Django 5.2.11 on 2026-02-08 09:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0001_initial"),
        ("qa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QADraftReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_draft_review",
                        to="datasets.job",
                    ),
                ),
            ],
        ),
    ]
