# Generated by Django 5.2.11 on 2026-02-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationclass",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
